Employees.create(name:"Erik Prenzlin", title:"CEO", department:"Management",experience:3,useful: false, salary:1000000) 
Employees.create(name:"Sofia Cotti", title:"COO", department:"Management",experience:1,useful: true, salary:900000)
Employees.create(name:"Dan Ellis", title:"Head of Legal", department:"Legal",experience:3,useful: true, salary:800000)
Employees.create(name:"Thomas Romain", title:"MD", department:"Analytics",experience:3,useful: false, salary:700000)
Employees.create(name:"Jean-Baptiste", title:"CRO", department:"Risk",experience:4,useful: false, salary:80000)
Employees.create(name:"Anna", title:"Executive Director", department:"Human Resources",experience:1,useful: false, salary:10)
Employees.create(name:"Sheldon Cooper", title:"Executive Director", department:"Quant",experience:5,useful: true, salary:600000)
Employees.create(name:"Howard Wolowitz", title:"Executive Director", department:"Quant",experience:3,useful: false, salary:500000)
Employees.create(name:"Penny", title:"Executive Director", department:"Sales",experience:2,useful: true, salary:600000)
Employees.create(name:"Amy", title:"Executive Director", department:"Quant",experience:2,useful: true, salary:500000)
Employees.create(name:"Micah Shute", title:"intern", department:"Developer",experience:5,useful: true, salary:nil)          
Employees.create(name:"Henrik Prenzlin", title:"Chairman", department:"Management",experience:1,useful: false, salary:nil) 
Employees.create(name:"Bali Kurt", title:"Head of Development", department:"Developer",experience:1,useful: false, salary:1000000) 